<a href="https://colab.research.google.com/github/ohimjosh/CSC-44800/blob/main/AS03/a3_sample_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

\(\^Be sure to update this button to point to your notebook instead of the sample notebook\)

In [23]:
# Imports section
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline

## Part 1. Loading the dataset

In [24]:
# Using pandas load the dataset (load remotely, not locally)
# Output the first 15 rows of the data
# Display a summary of the table information (number of datapoints, etc.)

data = pd.read_csv("https://raw.githubusercontent.com/profmcnich/example_notebook/main/science_data_large.csv")
data.head(15)

Temperature °C  Mols KCL     Size nm^3
0              469       647  6.244743e+05
1              403       694  5.779610e+05
2              302       975  6.196847e+05
3              779       916  1.460449e+06
4              901        18  4.325726e+04
5              545       637  7.124634e+05
6              660       519  7.006960e+05
7              143       869  2.718260e+05
8               89       461  8.919803e+04
9              294       776  4.770210e+05
10             991       117  2.441771e+05
11             307       781  5.006455e+05
12             206        70  3.145200e+04
13             437       599  5.390215e+05
14             566        75  9.185271e+04

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Temperature °C  1000 non-null   int64  
 1   Mols KCL        1000 non-null   int64  
 2   Size nm^3       1000 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 23.6 KB


## Part 2. Splitting the dataset

In [26]:
# Take the pandas dataset and split it into our features (X) and label (y)
X = data[["Temperature °C", "Mols KCL"]]
y = data["Size nm^3"]
# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.9, test_size=0.1)

In [27]:
X

Temperature °C  Mols KCL
0               469       647
1               403       694
2               302       975
3               779       916
4               901        18
..              ...       ...
995             894       847
996             327       982
997             791       213
998             769       553
999             919       452

[1000 rows x 2 columns]

In [28]:
y

0      6.244743e+05
1      5.779610e+05
2      6.196847e+05
3      1.460449e+06
4      4.325726e+04
           ...     
995    1.545661e+06
996    6.737041e+05
997    3.477543e+05
998    8.684794e+05
999    8.476413e+05
Name: Size nm^3, Length: 1000, dtype: float64

In [29]:
X_train

Temperature °C  Mols KCL
127             343       172
199             111       774
623             823       173
929             615       525
196             717       887
..              ...       ...
614             979       987
400             530       326
759             215       263
398             129        68
117             283       637

[900 rows x 2 columns]

In [30]:
X_test

Temperature °C  Mols KCL
1               403       694
244             404       641
716              95       499
448              36       151
539             874       827
..              ...       ...
98              847       340
63              580       817
766             282       311
739             240       402
982             347       274

[100 rows x 2 columns]

In [31]:
y_train


127    1.229533e+05
199    1.902765e+05
623    2.954891e+05
929    6.610050e+05
196    1.303041e+06
           ...     
614    1.972127e+06
400    3.549565e+05
759    1.176463e+05
398    1.922411e+04
117    3.755314e+05
Name: Size nm^3, Length: 900, dtype: float64

In [32]:
y_test

1      5.779610e+05
244    5.345155e+05
716    1.030643e+05
448    1.195546e+04
539    1.475625e+06
           ...     
98     5.894269e+05
63     9.737511e+05
766    1.815515e+05
739    2.004573e+05
982    1.964650e+05
Name: Size nm^3, Length: 100, dtype: float64

## Part 3. Perform a Linear Regression

In [33]:
# Use sklearn to train a model on the training set
reg = LinearRegression().fit(X_train, y_train)
# Create a sample datapoint and predict the output of that sample with the trained model

reg.predict(np.array([[300,350]]))

/home/ohimjosh/programming/CSC-44800/AS03/venv/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([204565.57391291])

In [34]:
# Report on the score for that model, in your own words (markdown, not code) explain what the score means
reg.score(X_train, y_train)

0.8623946650596183

The linear regression score of 0.8607117343929102 means that there is a 86.07% accuracy for our trained model. The goal is to get a score of 1.0 which is 100% accuracy of correctness.

In [35]:
# Extract the coefficents and intercept from the model and write an equation for your h(x) using LaTeX
reg.coef_

array([ 885.18909496, 1047.19833905])

In [36]:
reg.intercept_

-427510.57324368

h(x) : y = mx + b

h(x) : $θ_{0}$ + $θ_{1}$*$x_{1}$

h(x) : 876.43826102 * $x_{1}$ + 1025.93060778 * $x_{2}$ - 416335.79172673094


Sample equation: $E = mc^2$

## Part 4. Use Cross Validation

In [37]:
# Use the cross_val_score function to repeat your experiment across many shuffles of the data
scores = cross_val_score(reg, X, y, cv= 5)
scores

# Report on their finding and their significance

array([0.83918826, 0.87051239, 0.85871066, 0.87202623, 0.84364641])

In [38]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.86 accuracy with a standard deviation of 0.01


Looking at the outputs of the cross validation scores they are all around 0.8. The standard deviation is 0.01 meaning that our data is consistent and does not move at drastic intervals. The accuracy of the score is 0.86 which is also good since it is close to 1.0.

## Part 5. Using Polynomial Regression

In [39]:
# Using the PolynomialFeatures library perform another regression on an augmented dataset of degree 2
poly = PolynomialFeatures(degree= 2)
poly.fit_transform(X)
# Report on the metrics and output the resultant equation as you did in Part 3.

array([[1.00000e+00, 4.69000e+02, 6.47000e+02, 2.19961e+05, 3.03443e+05,
        4.18609e+05],
       [1.00000e+00, 4.03000e+02, 6.94000e+02, 1.62409e+05, 2.79682e+05,
        4.81636e+05],
       [1.00000e+00, 3.02000e+02, 9.75000e+02, 9.12040e+04, 2.94450e+05,
        9.50625e+05],
       ...,
       [1.00000e+00, 7.91000e+02, 2.13000e+02, 6.25681e+05, 1.68483e+05,
        4.53690e+04],
       [1.00000e+00, 7.69000e+02, 5.53000e+02, 5.91361e+05, 4.25257e+05,
        3.05809e+05],
       [1.00000e+00, 9.19000e+02, 4.52000e+02, 8.44561e+05, 4.15388e+05,
        2.04304e+05]])

In [40]:
model = Pipeline([('poly', PolynomialFeatures(degree=2)),
                  ('linear', LinearRegression(fit_intercept=False))])
model = model.fit(X_train, y_train)
model.named_steps['linear'].coef_

array([ 1.52531658e-05,  1.20000000e+01, -9.63598896e-08,  1.02708952e-11,
        2.00000000e+00,  2.85714287e-02])

In [41]:
model.predict(np.array([[300,350]]))

/home/ohimjosh/programming/CSC-44800/AS03/venv/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


array([217099.99999183])

In [42]:
model.score(X_train, y_train)

1.0

1.0 is the score that we are looking for which shows 100% accuracy. 

In [43]:
model.named_steps['linear'].intercept_

0.0

h(x) : 1.17188396e-05 * $x_{1}$ + 1.20000000e+01 * $x_{2}$ + -1.13958325e-07 * $x_{3}$ + -3.90745214e-11 * $x_{4}$ + 2.00000000e+00 * $x_{5}$ + 2.85714287e-02 * $x_{6}$ + 0