In [167]:
# Imports and pip installations (if needed)
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import svm 

# Part 1: Load the dataset

In [168]:
# Load the dataset (load remotely, not locally)
iris = datasets.load_iris()
data = pd.DataFrame(iris.data, columns= iris.feature_names)
# Output the first 15 rows of the data
data.head(15)
# Display a summary of the table information (number of datapoints, etc.)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
5                 5.4               3.9                1.7               0.4
6                 4.6               3.4                1.4               0.3
7                 5.0               3.4                1.5               0.2
8                 4.4               2.9                1.4               0.2
9                 4.9               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2
11                4.8               3.4                1.6               0.2
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
14                5.8               4.0                1.2               0.2

In [169]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?

# Part 2: Split the dataset into train and test

In [170]:
# Take the dataset and split it into our features (X) and label (y)
X = iris.data   #features
y = iris.target #label
# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size= 0.9, test_size=0.1)

In [171]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [172]:
X_train

array([[5. , 3.4, 1.5, 0.2],
       [6. , 2.7, 5.1, 1.6],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3.4, 4.5, 1.6],
       [6.8, 2.8, 4.8, 1.4],
       [5.9, 3. , 5.1, 1.8],
       [6.3, 3.4, 5.6, 2.4],
       [5.8, 2.6, 4. , 1.2],
       [6.7, 3.1, 4.4, 1.4],
       [7.2, 3. , 5.8, 1.6],
       [5.1, 2.5, 3. , 1.1],
       [7.9, 3.8, 6.4, 2. ],
       [7. , 3.2, 4.7, 1.4],
       [5. , 3. , 1.6, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [6.2, 3.4, 5.4, 2.3],
       [5.4, 3.9, 1.3, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.7, 2.5, 5. , 2. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 3.2, 4.5, 1.5],
       [6.3, 2.5, 5. , 1.9],
       [6.6, 2.9, 4.6, 1.3],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [4.6, 3.1, 1.5, 0.2],
       [6.4, 3.2, 5.3, 2.3],
       [7.7, 3.8, 6.7, 2.2],
       [5.9, 3. , 4.2, 1.5],
       [7.2, 3.2, 6. , 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [4.9, 2.5, 4.5, 1.7],
       [6. , 2

In [173]:
X_test

array([[6.7, 3.3, 5.7, 2.5],
       [6.6, 3. , 4.4, 1.4],
       [4.3, 3. , 1.1, 0.1],
       [5.5, 2.4, 3.8, 1.1],
       [4.9, 3.6, 1.4, 0.1],
       [6.1, 3. , 4.6, 1.4],
       [6.1, 2.6, 5.6, 1.4],
       [5.1, 3.8, 1.9, 0.4],
       [6.8, 3. , 5.5, 2.1],
       [5.6, 3. , 4.1, 1.3],
       [5.8, 2.8, 5.1, 2.4],
       [6.9, 3.1, 4.9, 1.5],
       [5.3, 3.7, 1.5, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [4.5, 2.3, 1.3, 0.3]])

In [174]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [175]:
y_train

array([0, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 0, 0, 2, 0, 0, 2, 1, 1, 1,
       1, 2, 1, 1, 1, 0, 2, 2, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 1, 0, 2, 0,
       2, 1, 1, 0, 0, 0, 0, 0, 1, 2, 1, 0, 1, 2, 1, 1, 2, 0, 2, 0, 1, 2,
       2, 0, 0, 1, 0, 2, 0, 1, 1, 0, 2, 1, 0, 2, 1, 0, 0, 2, 1, 1, 0, 2,
       2, 2, 2, 0, 0, 0, 0, 1, 0, 2, 0, 0, 1, 2, 2, 2, 2, 0, 1, 0, 0, 1,
       2, 2, 2, 1, 0, 2, 2, 1, 1, 0, 1, 1, 0, 0, 1, 0, 2, 1, 1, 0, 2, 2,
       2, 2, 1])

In [176]:
y_test


array([2, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 1, 0, 2, 0])

# Part 3: Logistic Regression

In [177]:

# i. Use sklearn to train a LogisticRegression model on the training set
reg = LinearRegression().fit(X_train, y_train)
reg.predict(X_test)

# ii. For a sample datapoint, predict the probabilities for each possible class

# iii. Report on the score for Logistic regression model, what does the score measure?

# iv. Extract the coefficents and intercepts for the boundary line(s)

array([ 2.16387408,  1.19638824, -0.10857977,  1.00427643, -0.13455046,
        1.27569337,  1.48197458,  0.1356206 ,  1.86104526,  1.15688438,
        2.08610968,  1.32690041, -0.08671412,  1.74642779,  0.08425598])

In [178]:
reg_pred = reg.predict(np.array([[0,5.1,3.5,1.4]]))
reg_pred

array([1.47760999])

In [179]:
reg.score(X_test, y_test)

0.9304797986348741

In [180]:
reg.coef_

array([-0.08437158, -0.05171125,  0.18559671,  0.68196424])

In [181]:
reg.intercept_

0.13699898202487182

# Part 4: Support Vector Machine

In [189]:
# i. Use sklearn to train a Support Vector Classifier on the training set
clf = svm.SVC(kernel='linear', probability=True)
clf.fit(X_train, y_train)
clf.predict(X_test)
# ii. For a sample datapoint, predict the probabilities for each possible class

# iii. Report on the score for the SVM, what does the score measure?

array([2, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 1, 0, 2, 0])

In [194]:
clf_pred = clf.predict(np.array([[0,5.1,3.5,1.4]]))
clf_pred


AttributeError: 'numpy.ndarray' object has no attribute 'predict'

In [193]:
clf.score(X_test, y_test)

AttributeError: 'numpy.ndarray' object has no attribute 'score'

# Part 5: Neural Network

In [183]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set

# ii. For a sample datapoint, predict the probabilities for each possible class

# iii. Report on the score for the Neural Network, what does the score measure?

# iv: Experiment with different options for the neural network, report on your best configuration (the highest score I was able to achieve was 0.8666)

# Part 6: K-Nearest Neighbors

In [184]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier

# ii. For a sample datapoint, predict the probabilities for each possible class

# iii. Report on the score for kNN, what does the score measure?

# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?